---
title: "strings_an_factors"
author: "Chuyue Xiang"
date: "10/15/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(p8105.datasets)

```

## String manipulation

```{r}
string_vec = c("my", "name", "is", "jeff")

str_detect(string_vec, "jeff") #find "" in the vec

```

```{r}
str_replace(string_vec, "jeff", "Jeff") # replace the letter or word
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "^i think") # "^" start with "i think"

str_detect(string_vec, "i think$") # "$" end with "i think"
```

```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"[Bb]ush") # detect Bush/bush
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]") #detect any numbers from 0-9 followed by letters
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11") #detect 7+any character ( a dot will match any character)+11
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[") # detect for "[", put "//"before that, one / is a special general expression
```

